version: '3.8'

services:
  websocket:
    container_name: websocket
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./scripts:/scripts
    command: python3 ./scripts/socket_python.py