version: "3.8"
services:
  apache:
    build: ./apache
    ports:
      - 8888:80
    volumes:
      - ./apache/www:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
